Ashenda Festival 2022: Home and about pagess
gtekle/Ashenda pull request #8
Opened 2021-12-22 15:52 UTC by gtekle

2021-12-22 17:21 UTC, DammyShittu requested changes
Hi @gtekle , 

YOU HAVE DONE AN AMAZING JOB SO FAR 👏 

To highlight,

- your UI design is amazing ✔️ 
- you have a well-structured code base ✔️ 
- you have a nicely written README file ✔️, and
- your presentation video was awesome ✔️ 
 
However, there are some issues that you still need to work on to get this project approved but you are almost there!


# REQUIRED CHANGES ♻️

- The `h1` tag is a really nice tag to use, but it's also very special. Just one `h1` tag is required per page to signify the main header. Kindly go through your HTML files and replace all other `h1` tags with other heading tags(h2 - h6). 😀 

- It would be nice to have some text in the `alt` attribute of the `img` tag. This would improve user experience, especially for people using screen readers, and also if the image fails to load due to one reason or the other.

_Check the comments under the review for more comments and suggestions_

# OPTIONAL SUGGESTIONS 🔢 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- For the mobile view, I noticed that the background color that was given to the navbar when it's in the fixed position almost blends with the background color of most sections of the page. What do you think about adding a darker color as the background color of that navbar? 😉 

# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 17:21 UTC, DammyShittu commented on README.md
> +- [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/)
- It's really nice that you added the `Acknowledgement` section. 😉 However, kindly acknowledge the author as stated in the requirements.

![](https://i.imgur.com/7faFGWN.png)

2021-12-22 17:21 UTC, DammyShittu commented on about.html
> +        <nav class="nav-menu">
Super cool navbar layout. Well done 👍 

I think you missed the little navigation bar at the top. 😀

Let's add it 👇

![](https://i.imgur.com/ns8Fdkk.png)

2021-12-22 17:21 UTC, DammyShittu commented on index.html
> +              centuries ago.
[OPTIONAL]
For the mobile view of the `Programs` section, what do you think about reducing the font-size of the sections to allow them to fit better within their cards? 😉

2021-12-22 21:00 UTC, gtekle commented
Hi @DammyShittu
Thank you very much for the detailed feedback. I have fixed both the required and the optional feedback that you gave me because I found all of them valuable.

2021-12-22 21:40 UTC, moise10r commented on about.html
> +        <nav class="nav-menu">
This issue is well addressed. Well done! :fireworks: :clap:

2021-12-22 22:01 UTC, moise10r approved these changes
## Hi @Ashenda, 

## **Congratulations! 🎉 Project Approved ✅**

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 👏👏👏 

 #### Optional suggestions
   * N/A

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-22 22:01 UTC, moise10r commented on index.html
> +        <!-- desktop menu -->
- [OPTIONAL ] Please remove this commented code, It is always a good practice to keep your code clean from such comments.

2021-12-22 22:01 UTC, moise10r commented on index.html
> +        <!-- mobile nav -->
- [OPTIONAL ] Please remove this commented code, It is always a good practice to keep your code clean from such comments.

2021-12-22 22:01 UTC, moise10r commented on index.html
> +          <!-- content is dynamically generated -->
- [OPTIONAL ] Please remove this commented code, It is always a good practice to keep your code clean from such comments.

2021-12-23 06:20 UTC, gtekle commented
Hi @moise10r
Thank you for the feedback. I have removed the comments in the `html` files for the code is self explanatory as per your suggestion.

2021-12-23 06:20 UTC, merged